version: '3'
services:
  envoy:
    build:
      context: ./
      dockerfile: ./docker/envoy/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
      - "9901:9901"

  node-server:
    build:
      context: ./
      dockerfile: ./docker/node_server/Dockerfile